version: 0.2

env:
  variables:
    FE_DIR: "pubg-insight-front"
    DIST_DIR: "pubg-insight-front/dist"
    HOSTING_BUCKET: "pubginfohub-bukket"
    CF_DISTRIBUTION_ID: "E2NQR3HITQJA37"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "== INSTALL =="
      - curl -fsSL https://rpm.nodesource.com/setup_22.x | bash -
      - yum install -y nodejs
      - node -v
      - npm -v
      - npm ci --prefix $FE_DIR

  pre_build:
    commands:
      - echo "== PRE_BUILD =="
      - |
        if [ -f "$FE_DIR/.env.production.template" ]; then
          cp "$FE_DIR/.env.production.template" "$FE_DIR/.env.production"
        fi

  build:
    commands:
      - echo "== BUILD =="
      - npm run build --prefix $FE_DIR

  post_build:
    commands:
      - echo "== POST_BUILD =="
      - aws s3 sync $DIST_DIR s3://$HOSTING_BUCKET --delete --exclude "map/*"
      - aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - pubg-insight-front/dist/**/*
cache:
  paths:
    - pubg-insight-front/node_modules/**/*
